
import pizza.enums.*;
import pizza.ordering.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Zahid Awan
 */
public class homeOrderForm extends javax.swing.JFrame {

    Order myOrder;
    /**
     * Creates new form homeOrderForm
     */
    public homeOrderForm() {
        myOrder = new Order();
        initComponents();
        
        jTextArea2.setText(myOrder.orderInfo());
        jTFOrderCost.setText( String.format("£%.2f",myOrder.totalCost()) );
        jEditPizzaButton.setEnabled(false); //make false at the end 
    }
    
    public void addToOrder(Pizza pizza){
        myOrder.addPizza(pizza);
        jTextArea2.setText(myOrder.orderInfo());
        jTFOrderCost.setText( String.format("£%.2f",myOrder.totalCost()) );
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jNewPizzaButton = new javax.swing.JButton();
        jEditPizzaButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTFOrderCost = new javax.swing.JTextField();
        jCloseButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jNewPizzaButton.setText("NEW PIZZA");
        jNewPizzaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNewPizzaButtonActionPerformed(evt);
            }
        });

        jEditPizzaButton.setText("EDIT / DELETE PIZZA");
        jEditPizzaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEditPizzaButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Total Order Cost:");

        jTFOrderCost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFOrderCostActionPerformed(evt);
            }
        });

        jCloseButton.setText("Close");
        jCloseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCloseButtonActionPerformed(evt);
            }
        });

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jTFOrderCost, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jCloseButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jNewPizzaButton)
                        .addGap(18, 18, 18)
                        .addComponent(jEditPizzaButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNewPizzaButton)
                    .addComponent(jEditPizzaButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTFOrderCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCloseButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jNewPizzaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNewPizzaButtonActionPerformed
        newPizzaForm newPizza = new newPizzaForm(this);
        newPizza.setVisible(true);
    }//GEN-LAST:event_jNewPizzaButtonActionPerformed

    private void jEditPizzaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEditPizzaButtonActionPerformed
        
        if(this.myOrder.numOfPizzas() == 0){
            
        }else{
        editPizzaForm editPizza = new editPizzaForm(this);
        editPizza.setVisible(true);  
        }
        
        
        
    }//GEN-LAST:event_jEditPizzaButtonActionPerformed

    private void jTFOrderCostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFOrderCostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFOrderCostActionPerformed

    private void jCloseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCloseButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_jCloseButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(homeOrderForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(homeOrderForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(homeOrderForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(homeOrderForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new homeOrderForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jCloseButton;
    public javax.swing.JButton jEditPizzaButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jNewPizzaButton;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTextField jTFOrderCost;
    public javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
}
