
import pizza.ordering.Pizza;
import pizza.enums.*;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Zahid Awan
 */
public class newPizzaForm extends javax.swing.JFrame {

    private homeOrderForm home;
    private Pizza newPizza;
    
    public newPizzaForm(homeOrderForm home) {
        initComponents();
        this.home = home;
        this.newPizza = new Pizza(Size.SMALL,
                Crust.THIN,
                Sauce.TOMATO,
                Topping.NONE,
                Topping.NONE );
        jTextArea1.setText(newPizza.getInfo());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTop1CB = new javax.swing.JComboBox<>();
        jSizeCB = new javax.swing.JComboBox<>();
        jCrustCB = new javax.swing.JComboBox<>();
        jTop2CB = new javax.swing.JComboBox<>();
        jSauceCB = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jCancelButton = new javax.swing.JButton();
        jAddToOrderButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Size");

        jLabel2.setText("Crust");

        jLabel3.setText("Topping 1");

        jLabel4.setText("Topping 2");

        jLabel5.setText("Sauce");

        jTop1CB.setModel( new javax.swing.DefaultComboBoxModel(Topping.values()));
        jTop1CB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTop1CBActionPerformed(evt);
            }
        });

        jSizeCB.setModel( new javax.swing.DefaultComboBoxModel(Size.values()));
        jSizeCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSizeCBActionPerformed(evt);
            }
        });

        jCrustCB.setModel( new javax.swing.DefaultComboBoxModel(Crust.values()));
        jCrustCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCrustCBActionPerformed(evt);
            }
        });

        jTop2CB.setModel( new javax.swing.DefaultComboBoxModel(Topping.values()));
        jTop2CB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTop2CBActionPerformed(evt);
            }
        });

        jSauceCB.setModel( new javax.swing.DefaultComboBoxModel(Sauce.values()));
        jSauceCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSauceCBActionPerformed(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jCancelButton.setText("Cancel");
        jCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCancelButtonActionPerformed(evt);
            }
        });

        jAddToOrderButton.setText("Add to Order");
        jAddToOrderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddToOrderButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jCrustCB, 0, 143, Short.MAX_VALUE)
                                    .addComponent(jSizeCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(36, 36, 36)
                                .addComponent(jSauceCB, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCancelButton)
                                .addGap(18, 18, 18)
                                .addComponent(jAddToOrderButton)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jTop1CB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jTop2CB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jSizeCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jCrustCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jSauceCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTop1CB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTop2CB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCancelButton)
                    .addComponent(jAddToOrderButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCancelButtonActionPerformed
       this.setVisible(false);
       
    }//GEN-LAST:event_jCancelButtonActionPerformed

    private void jAddToOrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddToOrderButtonActionPerformed
        // TODO add your handling code here:
        home.addToOrder(new Pizza(
                (Size) jSizeCB.getSelectedItem(),
                (Crust) jCrustCB.getSelectedItem(),
                (Sauce) jSauceCB.getSelectedItem(),
                (Topping) jTop1CB.getSelectedItem(),
                (Topping) jTop2CB.getSelectedItem()
        ));
        
        home.jEditPizzaButton.setEnabled(true);
        this.setVisible(false);
    }//GEN-LAST:event_jAddToOrderButtonActionPerformed

    private void jSizeCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSizeCBActionPerformed
        this.newPizza.setSize((Size) jSizeCB.getSelectedItem());
        jTextArea1.setText(newPizza.getInfo());
    }//GEN-LAST:event_jSizeCBActionPerformed

    private void jCrustCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCrustCBActionPerformed
        this.newPizza.setCrust( (Crust) jCrustCB.getSelectedItem());
        jTextArea1.setText(newPizza.getInfo());
    }//GEN-LAST:event_jCrustCBActionPerformed

    private void jTop2CBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTop2CBActionPerformed
        this.newPizza.setTopping2( (Topping) jTop2CB.getSelectedItem());
        jTextArea1.setText(newPizza.getInfo());
    }//GEN-LAST:event_jTop2CBActionPerformed

    private void jSauceCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSauceCBActionPerformed
        this.newPizza.setSauce( (Sauce) jSauceCB.getSelectedItem());
        jTextArea1.setText(newPizza.getInfo());
    }//GEN-LAST:event_jSauceCBActionPerformed

    private void jTop1CBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTop1CBActionPerformed
        this.newPizza.setTopping1( (Topping) jTop1CB.getSelectedItem());
        jTextArea1.setText(newPizza.getInfo());
    }//GEN-LAST:event_jTop1CBActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(newPizzaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(newPizzaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(newPizzaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(newPizzaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new newPizzaForm().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAddToOrderButton;
    private javax.swing.JButton jCancelButton;
    private javax.swing.JComboBox<String> jCrustCB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JComboBox<String> jSauceCB;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jSizeCB;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JComboBox<String> jTop1CB;
    private javax.swing.JComboBox<String> jTop2CB;
    // End of variables declaration//GEN-END:variables
}
